version: '3.8'

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: Localhost:3307
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ticket_db
    ports:
      - "3000:3000"

volumes:
  db_data:
