services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_db
    ports:
      - "3308:3307"  # Host port 3308 maps to container port 3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db:3307  # Use the service name 'db' to connect to the MySQL container
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ticket_db
    ports:
      - "3000:3000"

volumes:
  db_data:
